### ISSUE TITLE
B014 recommends `except ():`

### ISSUE THREAD

**Issue by robinst** [PyCQA/flake8-bugbear#110]
In the following code:

```
    try:
        with open(fn) as f:
            return f.read().split('\n')
    except (OSError, IOError):
        pass
```

The new B014 warning shows this:

> B014 Redundant exception types in `except (OSError, IOError):`.  Write `except ():`, which catches exactly the same exceptions.

Doesn't seem to make sense to me. Is this a bug :bear:?

**Comment by cooperlees** [comment]
Thanks for the report, seems buggy to me. If someone does not beat me, I'll try add a test in the next few days and see if I can work out the bug.

**Comment by AlexandreYang** [comment]
I guess you are using Python3.

We encountered the same case: https://github.com/DataDog/integrations-core/pull/5389

That's because in Python 3 `OSError` and `IOError` are equal.

```
$ python2 -c "print(OSError == IOError)"
False
$ python3 -c "print(OSError == IOError)"
True
```

In our case, we still need to support both Python 2 and Python 3 for now, hence we chose to `# noqa: B014` that line.

## Details

For Python 3:

> Changed in version 3.3: EnvironmentError, IOError, WindowsError, socket.error, select.error and mmap.error have been merged into OSError, and the constructor may return a subclass.

But in Python 2 `IOError` and `OSError`  are still conceptually two different error classes.

```
BaseException
 +-- Exception
      +-- StandardError
      |    +-- EnvironmentError
      |    |    +-- IOError
      |    |    +-- OSError
      |    |         +-- WindowsError (Windows)
      |    |         +-- VMSError (VMS)
```
source: https://docs.python.org/2/library/exceptions.html

**Comment by cooperlees** [comment]
Thanks for the insightful explanation.

**Comment by deveshks** [comment]
Is there any other fix for this issue if the code in question supports both Python 2 and Python 3 apart from adding `# noqa: B014` ?
