### ISSUE TITLE
Erroneous report message in B014

### ISSUE THREAD

**Issue by neutrinoceros** [PyCQA/flake8-bugbear#126]
flake8 reports on this line
```python
    except (IOError, OSError, ImportError):
```
with
```
B014 Redundant exception types in `except (IOError, OSError, ImportError):`.  Write `except ImportError:`, which catches exactly the same exceptions.
```

I believe this message is incorrect, as is demonstrated by the following snippets

```python
try:
    raise OSError
except ImportError:
    print("gotcha")
# OSError is raised
```

```python
try:
    raise IOError
except ImportError:
    print("gotcha")
# IOError is raised
```

However
```python
try:
    raise OSError
except IOError:
    print("gotcha")
# ... "gotcha"
```

```python
try:
    raise IOError
except OSError:
    print("gotcha")
# ... "gotcha"
```

So  the original line is indeed redundant, but the report message is misleading

**Comment by cooperlees** [comment]
@Zac-HD - Got any cycles to dig into this one please ?

**Comment by Zac-HD** [comment]
Eeek, that's not good.  

Currently on a road trip with limited compute and network access (outback Australia!), but it'll be top priority when I get home.  The bug is somewhere in 

https://github.com/PyCQA/flake8-bugbear/blob/b4809174d60159e095104f34c44d484e87264394/bugbear.py#L181-L189

which should probably just use less-clever code with an explicit loop: start with an empty `good` list; for each exception E remove any elements which are subclasses of E and then append E.

**Comment by ambv** [comment]
Gentlemen, in Python 3 IOError is an alias for OSError. The check is correct.

**Comment by neutrinoceros** [comment]
I am not denying that. The problem is that flake8 is wrongly suggesting that ImportError is also an alias of IOError.
