### ISSUE TITLE
Suggest `!r` format specifier for strings like `f"foo is '{self.foo}'"`

### ISSUE THREAD

**Issue by Zac-HD** [PyCQA/flake8-bugbear#319]
I've seen some code lately where a reminder about the `!r` format specifier would probably have helped - instead of displaying the repr, single-quotes were manually added outside the braces as in `f"No value found at '{path}'"`.  This OK, _until_ `path` contains a single-quote character and then it can get confusing fast.

I'd therefore propose warning about this case, which is conveniently easy to reliably detect [using the `JoinedStr` and `FormattedValue` nodes](https://docs.python.org/3/library/ast.html#ast.FormattedValue) - within a `JoinedStr`, warn if there is a sequence of `Constant`/`FormattedValue`/`Constant`, where the first constant ends and the second starts with a single or double quote character, and the formatter value has no conversion code.

Separately, I used the regex `".*('\{[^}]+\}').*"` to confirm that this is common enough to be worth linting for.  It's not especially rare, and IMO pretty useful to teach people about format specifiers.

**Comment by cooperlees** [comment]
I see no reason as long as we can make this not noisy and you logic seems to cater for that. If someone wants to put up a PR with lots of tests showing it's not noisy I'm all for it.

**Comment by jakkdl** [comment]
A couple weird edge cases:
1. `f'"{var1}"{var2}"'`
should this warn on `var1`, both, or neither? My PR currently warns on the first one, it's trivial to change it to warn on both, but warning on neither would require some fancy logic.


2. `f'""{var}""'`
if a user is doing multiple quotes, it feels intentional, though kinda weird. Should the check make sure to avoid triggering on this or is it a fine false alarm? PR currently doesn't check for this but wouldn't be too hard to.


3. "[...] and the formatter value has no conversion code."
If somebody is doing `f'"{...!s}"'` they should probably do `f'{str(...)!r}'` (and same with `!a`) - so I think it should only be silenced if the conversion code is `!r`.

**Comment by Zac-HD** [comment]
1. So long as we get *a* warning here, I don't care much which; so just-the-first is fine.
2. (and 4). we're trying to lint for 'don't manually add string quotes', so if it's not a valid `', ", ''', or """` I guess we could be silent?
3. OK, no conversion code *or !s or !a*; if we see [one of the many numeric specifiers](https://docs.python.org/3/library/string.html#formatspec) then the quotes are presumptively OK.
