### ISSUE TITLE
B028 should suggest underlying functions instead of obscure flags

### ISSUE THREAD

**Issue by kalekseev** [PyCQA/flake8-bugbear#332]
B028 introduced in #319 should suggest `repr` instead of `!r` for readability, these flags were preserved in f-string only for backward compatibility with `.format()`, from PEP 498 [!s, !r, and !a are redundant](https://peps.python.org/pep-0498/#s-r-and-a-are-redundant)

**Comment by kalekseev** [comment]
Overall, I believe B028 in current form is more harmful than useful, using `repr` to wrap in quotes is a hack that is unreadable and unreliable https://github.com/PyCQA/flake8-bugbear/issues/329.
The `repr` only used because of the lack of specific functions in stdlib, something like `textwrap.single_quotes()` and `textwrap.double_quotes()`.

**Comment by jakkdl** [comment]
Hmm, I actually find this somewhat convincing. @Zac-HD have you considered `repr()` instead of `!r`?

@kalekseev the original reasoning behind the flag is https://github.com/PyCQA/flake8-bugbear/issues/319 to handle quotes inside strings. Though given the number of opened issues it does seem like it should be turned into an optional warning or require several other changes.

**Comment by Zac-HD** [comment]
Per https://github.com/PyCQA/flake8-bugbear/issues/331#issuecomment-1384005181, let's disable it by default.
